### ISSUE TITLE
Remove .deb files from repo

### ISSUE THREAD

**Issue by jmcejuela** [Rostlab/TMSEG.backup#1]
Congrats, your tool is actually already on github: https://github.com/BernhoferM/TMSEG2 and documented on the rostlab wiki: https://rostlab.org/owiki/index.php/Tmseg

As you see though, there are those nasty binary .deb files that should not be in the main repository. At least not in the root folder. They should like be placed as downloadable files.

* [ ] Remove or move to appropriate place the .deb files (Note, not for Nov 5, but more in upcoming weeks)

**Comment by jmcejuela** [comment]
@Bernhofer FYI we're moving and improving Rostlab tools to the official github organization

**Comment by jmcejuela** [comment]
@BernhoferM FYI

**Comment by Startouf** [comment]
So what should we do about the github ? Pull from Bernhofer URL and push back on this Rostlab/TMSEG repo ?

I actually suggest removing the current `https://github.com/Rostlab/TMSEG` repository, and replace it by forking `https://github.com/BernhoferM/TMSEG2` into the ROSTLAB organizations. It will make something clean while keeping the references "this repository was forked from ...". Then we can make the cleanup of .deb files and others, and there will still be somewhere a reference to the original repo.

Also should we keep TMSEG as a name, or TMSEG2 ? (the URL you gave points to a repo named TEMSEG2)

**Comment by jmcejuela** [comment]
@Startouf @BernhoferM 

See my comment in original repo: https://github.com/BernhoferM/TMSEG2/issues/1#issuecomment-153343838

As for forking the original repo, either:

* I transfer myself the repo to the Rostlab organization (@BernhoferM for that I either first clone your repo or you give me the ownership of the repo, but I don't think the latter is fair ;))
* **I clone your original repo as suggested by @Startouf (by recreating this repo) -- probably the easiest and cleanest solution**
* or, the students simply clone the original repo onto their local machines, and push the code to this repo

@BernhoferM please let me know.

**Comment by jmcejuela** [comment]
As for the name:

I suggest calling the repo and method "TMSEG" (or in lower case if your prefer @BernhoferM).

We can then create and release different versions. @BernhoferM You could help me in this and tag the exact commit that you consider 1.0 and tag the exact commit you consider 2.0.

**Comment by BernhoferM** [comment]
@jmcejuela 
- Moving: I guess your option 2 (cloning the repository) is the best solution.
- Name: TMSEG (as it is now) is just fine.
- Versions: v1.0 was never commited to the git repository. As such, all commits are for v2.0.0

There will be an update (v2.1) within the next week. New prediction models and some fixes to the algorithm.

**Comment by jmcejuela** [comment]
:+1: will do

@Startouf ping me if I forget -- I'm busy with sth else right now :P

**Comment by jmcejuela** [comment]
(copied from email; Please use github communication):

```
Hello,

Sorry I've been busy and I didn't realize it before, but you had asked
me to ping you for transferring the repo TMSEG from @BernhoferM to here.

The idea was to delete the actual Rostlab/TMSEG repo so we could do a
clean fork of BernhoferM/TMSEG2. I'm not sure I can actually delete the
current Rostlab/TMSEG repo myself because of privilege restrictions. I
didn't understand when this was expected to happen though.

Also, @BernhoferM did mention there would be an update coming the next
week, so maybe it's better if we leave it like this for now and only do
the fork/transfer next week (or maybe on the opposite it's an occasion
to give it a try to see if your suggestion of master/develop/featuress
branch works well) ?

We will just write the readme.md locally in our computer in the meantime
until this gets sorted.

Regards,

--
Cyril Duchon-Doris
```

**Comment by jmcejuela** [comment]
* I renamed this project with the appendix `.backup` just in case. @Startouf @mkeribin Let me know when we can delete the repo altogether
* I create now another TMSEG project by forking Michael's
* We work with the branching model `master & develop & features` and you guys work at the same time. Please all (@Startouf @mkeribin @BernhoferM ) work on feature branches for your changes. Then they get merged to develop. Then the get merged to master for releases (and we will have 2.1 soon).

**Comment by jmcejuela** [comment]
--> https://github.com/Rostlab/TMSEG
